lesson 3
kerni2/RoR-base pull request #2
Opened 2022-07-08 14:03 UTC by kerni2

2022-07-08 17:48 UTC, BubuntuClu requested changes

2022-07-08 17:48 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "correct", default: 0
это будевое поле. ответ может быть либо правильный, либо неправильный

2022-07-08 17:48 UTC, BubuntuClu commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2022_07_08_134228) do
во всех таблицах забыл указать внешние ключи

2022-07-09 09:53 UTC, kerni2 commented on db/schema.rb
> +    t.integer "correct", default: 0
поправил

2022-07-09 09:53 UTC, kerni2 commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2022_07_08_134228) do
добавил

2022-07-10 10:54 UTC, merged