lesson9
kerni2/RoR-base pull request #8
Opened 2022-08-02 16:01 UTC by kerni2

2022-08-02 16:54 UTC, BubuntuClu requested changes

2022-08-02 16:54 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    count.zero? ? result = 0 : result = (correct_questions * 100 / count)
зачем тут `result = `?  это же последняя строка метода.

вообще присваивание выносят из выражения
`result = count.zero? ? 0 : (correct_questions * 100 / count)`

2022-08-02 16:54 UTC, BubuntuClu commented on db/migrate/20220801093446_drop_table_progresses.rb
> +  def up
если есть метод `up`, то должен быть и метод `down`, чтобы при откатывании миграции не словить ошибку.
в данном случае, метод `down` можно оставить пустым

2022-08-03 09:39 UTC, kerni2 commented on db/migrate/20220801093446_drop_table_progresses.rb
> +  def up
поправил

2022-08-03 09:39 UTC, kerni2 commented on app/models/test_passage.rb
> +    count.zero? ? result = 0 : result = (correct_questions * 100 / count)
поправил

2022-08-03 09:40 UTC, merged